# Generated by Django 4.1.4 on 2022-12-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_item_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='States',
            fields=[
                ('states_id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'states',
            },
        ),
    ]
