# Generated by Django 4.1.4 on 2022-12-14 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_states'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='states',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.states'),
        ),
    ]
